#!/bin/bash 
/bin/bash helper_1.sh &
/bin/bash helper_2.sh &
/bin/bash helper_3.sh &
/bin/bash helper_4.sh &
/bin/bash helper_5.sh &
/bin/bash helper_6.sh &
/bin/bash helper_7.sh &
/bin/bash helper_8.sh &
/bin/bash helper_9.sh &
/bin/bash helper_10.sh &
/bin/bash helper_11.sh &
/bin/bash helper_12.sh &
/bin/bash helper_13.sh &
/bin/bash helper_14.sh &
/bin/bash helper_15.sh &
/bin/bash helper_16.sh &
/bin/bash helper_17.sh &
/bin/bash helper_18.sh &
/bin/bash helper_19.sh &
/bin/bash helper_20.sh &
/bin/bash helper_21.sh &
/bin/bash helper_22.sh &
/bin/bash helper_23.sh &
/bin/bash helper_24.sh &
/bin/bash helper_25.sh &
/bin/bash helper_26.sh &
/bin/bash helper_27.sh &
/bin/bash helper_28.sh &
/bin/bash helper_29.sh &
/bin/bash helper_30.sh &
/bin/bash helper_31.sh &
/bin/bash helper_32.sh &
/bin/bash helper_33.sh &
/bin/bash helper_34.sh &
/bin/bash helper_35.sh &
/bin/bash helper_36.sh &
/bin/bash helper_37.sh &
/bin/bash helper_38.sh &
/bin/bash helper_39.sh &
/bin/bash helper_40.sh &
